# collections
collections:
  recipes:
    title: Recipes
    output: true
  uploads:
    title: Uploads
    output: true

# SITE CONFIGURATION
baseurl: "" #leave this alone
url: "https://yoursite.github.io" #change this to yours
title: Your recipe collection
recipemenu: false # you can change to true and a menu of all recipes will appear
favicon: assets/favicon.ico
recipe_bookcover: /uploads/bookcover.jpg
# change the following to your name or site name
footer_text:
  "Copyright 2020 My name"

# Localization strings
str_follow_on: "Follow on"
str_rss_follow: "Follow RSS feed"
str_share_on: "Share on"
str_add_to: "Add to"
str_email: "Email"
str_tweet: "Tweet"
str_pin_it: "Pin it"
str_next_post: "Next post"
str_previous_post: "Previous post"
str_next_page: "Next"
str_previous_page: "Prev"
str_javascript_required_disqus: "Please enable JavaScript to view comments."

# BUILD SETTINGS
markdown: kramdown
permalink: pretty
highlighter: rouge
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]
exclude: [".jekyll-cache", "Gemfile", "README.md"]
excerpt_separator: <!--more--> # Leave this because this controls the extract from the recipe on the listing page
lang: en_gb

prose:
    # rooturl: '_recipes'
    ignore:
      - _config.yml
      - /_layouts
      - /_includes
      - /pages
      - /assets
      - /resources
    media: "_uploads"
    metadata:
      _recipes:
        - name: "layout"
          field:
            element: "hidden"
            value: "recipe"
        - name: "title"
          field:
            element: "text"
            label: "title"
            help: "Put the title of your recipe here"

